---
variables:
  DOCKER_BUILDKIT: 1

stages:
- build

build_release:
  rules:
  - if: $CI_COMMIT_TAG
    when: always
  stage: build
  image: docker:latest
  services:
  - docker:dind
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

build_head:
  stage: build
  image: docker:latest
  services:
  - docker:dind
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker build -t $CI_REGISTRY_IMAGE:latest-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA .
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker push $CI_REGISTRY_IMAGE:latest-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
